name: build-book-01

on:
  push:
    branches: [ "master" ]
    paths:
      - 'book-01/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'book-01/**'
  workflow_dispatch:

env:
  BUILD_AVX512: 0
  PROJ_DIR: 'book-01'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-architecture: x64

    - name: Build
      # Add additional options to the MSBuild command line here.
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild '${{github.workspace}}\${{env.PROJ_DIR}}\Study.sln' /m /p:Configuration=Release /p:platform=x64

    - name: Test
      uses: microsoft/vstest-action@v1.0.0
      with:
        searchFolder: '${{github.workspace}}\${{env.PROJ_DIR}}\'
        platform: 'x64'
